version: '2'
services:
  app:
    image: php:8.1-apache
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: planos_zumtalk
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planos_zumtalk
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: